#!/bin/bash

gnuplot -e "set term png" -e "set output \"results/layout_00.png\"" -e "plot \"results/00.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_01.png\"" -e "plot \"results/01.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_02.png\"" -e "plot \"results/02.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_03.png\"" -e "plot \"results/03.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_04.png\"" -e "plot \"results/04.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_05.png\"" -e "plot \"results/05.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_06.png\"" -e "plot \"results/06.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_07.png\"" -e "plot \"results/07.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_08.png\"" -e "plot \"results/08.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_09.png\"" -e "plot \"results/09.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_obs_00.png\"" -e "plot \"results/obs_00.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_obs_01.png\"" -e "plot \"results/obs_01.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_obs_02.png\"" -e "plot \"results/obs_02.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_obs_03.png\"" -e "plot \"results/obs_03.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_obs_04.png\"" -e "plot \"results/obs_04.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_obs_05.png\"" -e "plot \"results/obs_05.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_obs_06.png\"" -e "plot \"results/obs_06.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_obs_07.png\"" -e "plot \"results/obs_07.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_obs_08.png\"" -e "plot \"results/obs_08.xml\""
gnuplot -e "set term png" -e "set output \"results/layout_obs_09.png\"" -e "plot \"results/obs_09.xml\""
